config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root to: 'events#index'
  devise_for :users
 # root to: 'users#index' #brings to https://polar-escarpment-85363.herokuapp.com/ 

 resources :users
 resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

	#Relation 1-N entre la table jointe attendances et les 2 tables users et events. 
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord

	#relation N-N entre events et users donc passage par la table jointe attendances
	has_many :attendances 
	has_many :users, through: :attendances

	#2)on implemente la methode class_name dans le model Event
	belongs_to :admin, class_name: "User"

	#Les validations des attributs
	validates :start_date, presence: true 
	validates :duration, presence: true
	validates :description, presence: true, length: { in: 20..1000, message: "La descripton doit avoir entre 20 et 1000 caracteres"}  #on valide la presence de la description de l event si ce dernier respecte une longueur comprise entre 20 et 1000
	validates :title, presence: true, length: { in: 5..140, message: "Le titre doit comprendre entre 5 et 140 caracteres"} 
	validates :location, presence: true
    validates :price, presence: true, numericality: { in: 1..1000, message: "Le prix doit etre entre 1 et 1000"}



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	after_create :welcome_send

	
	#Relation N-N entre les tables events et users doc necessite de passer par table jointe attendances
	has_many :attendances
	has_many :events, through: :attendances 


	#3)dans la classe User on dit que user a plusieurs event_administrators(admins), ces administrators correspondent a la colonne admin_id dans le model Event
	has_many :event_admins, foreign_key: 'admin_id', class_name: "Event" 


  	def welcome_send
   	 UserMailer.welcome_email(self).deliver_now
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show]

    def index
  	    # Méthode qui récupère tous les evenements et les envoie à la view index (index.html.erb) pour affichage
   	  @events = Event.all
    end
 
   def new
 	    # Méthode qui crée un Evenement vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    @event = Event.new
    end

    def show
    	    # Méthode qui récupère l evenement  concerné et l'envoie à la view show (show.html.erb) pour affichage
    @event = Event.find(params[:id])
  	end

    def create
    # Méthode qui créé un evemenent à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)

    #on verifie que le formulaire envoie bien les params saisis code entre les puts $ non necessaire , mais qui nous permet de checker au debut 
    puts "$" * 60
    puts "ceci est le contenu de params et signifie que le formulaire pointe bien sur create :"
    puts params
    puts "$" * 60

    #le code suivant est le code a rentrer dans $ rails c afin de creer en BDD un user test un event test qui a donc ce user associe. et on check si il y les rollbacks et si ca marche bien
    #e = Event.new(blabla)
    #e.save
    #sil n y a pas de rollbacks notre save est bien effectue et notre @event sauve en BDD
    @event = Event.new(start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location], admin_id: 1)
 #=> {:title=>["must exist"], :title=>["is too short (minimum is 3 characters)"], :content=>["can't be blank"] etc exemple de rollbacks}

    if @event.save # essaie de sauvegarder en base @event
      flash[:success] = "The super Event was succesfully saved !"
    # si ça marche, il redirige vers la page d'index du site
        redirect_to events_path #redirect_to va passer   /   eventss#index cf $ rails routes | grep root

  else
    # sinon, il render la view new (qui est celle sur laquelle on est déjà)
    render :new
  end
end

    def edit
    end

    def update
    end

    def destroy
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 #le helper authenticate_user donne acces au callback, seul un authenticate_user peut acceder a la page show qui montre le profil du user

	  before_action :authenticate_user!, only: [:show]

  def show

  	  # Méthode qui récupère le user concerné et l'envoie à la view show (show.html.erb) pour affichage

    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<html>
<!-- On met le flash ici pour que dans la view qui affiche les events puisse s executer les codes flash du controller events-->
<% flash.each do |key, value| %>
  <div class="alert alert-success" role="alert">
    <%= value %>
  </div>
<% end %>
<body>
  <h1> --- WELCOME IN EVENT BRITE A TOULOUSE --- </h1>
  <% if user_signed_in? %> <!-- ICI ON CALE NOTRE HELPER user_signed_in?dans l ancien projet c est le hash session avec la condition if session[:user_id] -->
  <h1> cher(e) <%= current_user.email %>  </h1>
   <%end%>

  <!-- ici on cree le bouton qui clique va nous amener au formulaire -->
  <p> <%=link_to "Créer un événement", new_event_path, class: "btn btn-primary btn-lg" %> </p>
  

  <div class="container" style="display: flex; flex-wrap: wrap; justify-content: space-around; padding-top: 120px">
    <% @events.each do |event| %>
      <div class="card text-white bg-secondary mb-3" style="width: 30rem;">
        <div class="card-header"> Date de l event : <%= event.start_date %> </div>
        <div class="card-body">
          <h5 class="card-title">Titre de l event : <%= event.title %></h5>
         <p> Lieu : <%=event.location%> </p>
               <%= link_to 'Voir', event_path(event.id), class: 'btn btn-secondary bg-info' %> <!--    event GET    /events/:id(.:format)                                                                    events#show ca nous renvoie a def show de events_controller ou on va recuperer l evenement particulier grace a find, et ensuite executer la view show.html.erb de  la view event
-->
          <div class="card-footer"> </div>
        </div>
      </div>
    <% end %>
  </div>

</body>
</html>

app/views/events/new.html.erb
<% if @event.errors.any? %>
 <!-- Alerte Bootstrap a mettre dans notre view, elle s execute depuis le controller events-->
  <div class="alert alert-danger" role="alert">
    <p>Nous n'avons pas réussi à créer l event pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>



<!--Le formulaire va POINTER vers la methode #create dans le controller events Jamy, nous dit c'est pas super intuitif, mais PAR CONVENTION le POST de création va à /events et non pas /events/new -->
    <h1 class="display-4">Créer un evenement</h1>
  
<%= form_tag url_for(action: 'create'), method: "post" do %>

  <div class="form-group">
    <%= label_tag(:title, "Titre :") %>
    <%= text_field_tag(:title,"", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:description, "Description :") %>
    <%= text_area_tag(:description,"", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:location, "Lieu :") %>
    <%= text_field_tag(:location, "", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:price, "Prix :") %>
    <%= text_field_tag(:price, "", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:start_date, "Début:") %>
    <%= text_field_tag(:start_date, Time.now+1000 , :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:duration, "Durée:") %>
    <%= text_field_tag(:duration,"",:class => 'form-control')%>
  </div>

		<div class="col-sm-12 d-flex justify-content-center  m-3">
			<%= submit_tag("Confirmer l'évènement", :class => "btn btn-primary") %>
		</div>

<% end %>

app/views/events/show.html.erb
<html>


  <title>
      Page Event
  </title>

  <body>

    <div class="jumbotron">

      <h3>PAGE EVENT</h3>
        <p>Voici la page de l evenement <%=@event.title %>, cree le <%= @event.created_at %></p> 

          <!-- Affiche les infos de l evenement -->
        <p class="lead"> Titre : <%=@event.title %> </p>
        <p class="lead"> Description : <%= @event.description %> </p>
        <p class="lead"> Titre : <%=@event.title %> </p>
        <p class="lead"> Date : <%= @event.start_date %> </p>
        <p class="lead"> Duree : <%=@event.duration %> </p>
        <p class="lead"> Prix : <%= @event.price %> Euros</p>
        <p class="lead"> Lieu : <%=@event.location %> </p>

  
  
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheEventBriteLikePoject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>

<!-- Ajout CDN BOOTSTRAP -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  
    <!-- Ajout Header et Navbar -->
        <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-primary">

           <a class="navbar-brand" href="<%= root_path%>">TOULOUSE EVENTS</a>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">           
                 <li class="nav-item">
                   <%= link_to "Accueil", events_path, class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Créer un evenement", new_event_path, class: "nav-link" %> <!-- new_event GET    /events/new(.:format)                                                                    events#new
 -->
                 </li>
                 <li class="nav-item">
                 <% if user_signed_in?  %> <!-- Si l utilisateur est connecte, alors un onglet profil apparait dans la navbar des quil sera deconnecte, le profil disparatra-->

                  <%= link_to "Mon profil", user_path(current_user.id), class: "nav-link" %> <!--  user GET    /users/:id(.:format)                                                                     users#show
 
 -->            <% end %>
                </li>

                </ul>
              </div>

            <div>
                  <!-- ul pour le login -->
               <ul class= "nav navbar-nav navbar-right">
                  <% if current_user == nil %>

                  <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
                      User
                    </button>
                       <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
                          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
                       </div>
                 </div>
               
                <li class="nav-item">
                <% else %>           
                  
                  <!-- on appelle la methode destroy du controller sessions      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
-->
                 <%= link_to "Se deconnecter",destroy_user_session_path, :class => "nav-link", method: :delete %> 

              <% end %>
           </li>
          </ul>
        </div>      
      </nav>

    <%= yield %>

  
</html>

app/views/users/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Profil </h1>
    
  </div>
</div>
  <p> 
  Nom :  <%= @user.last_name %> <%= @user.first_name %><br/>
  Description : <%= @user.description %> <br/>
  Mail : <%= @user.email %><br/>
  </p>
  

  <p> <%=link_to "Créer un événement", new_event_path, class: "btn btn-primary btn-lg" %> </p> <!--  new_event GET    /events/new(.:format)             events#new
-->

  <p> <%=link_to "Changer mon mot de passe", edit_user_registration_path, class: "btn btn-primary btn-lg" %>  </p> <!--   edit_user_registration GET    /users/edit(.:format)      devise/registrations#edit
-->